"""create_template_sets_tables

Revision ID: 17850b0b9ab9
Revises: 5273e4af6641
Create Date: 2026-06-03 01:42:18.150411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17850b0b9ab9'
down_revision: Union[str, Sequence[str], None] = '5273e4af6641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_sets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shared_fields',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_set_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('field_label', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=True),
    sa.Column('field_order', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('default_value', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['template_set_id'], ['template_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_set_members',
    sa.Column('template_set_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_set_id'], ['template_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_set_id', 'template_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_set_members')
    op.drop_table('shared_fields')
    op.drop_table('template_sets')
    # ### end Alembic commands ###
